import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google';

const inter = Inter({
    subsets: ['latin'], // İhtiyacınıza göre "latin" veya "latin-ext"
    variable: '--font-inter', // CSS değişkeni olarak ekleme
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={inter.variable} >
      <body >
        {children}
      </body>
    </html>
  );
}
