import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google';
import Main from "@/app/components/Main";
import './css/extra.css'

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={inter.variable} >
      <body >
      <Main>
          {children}
      </Main>


      </body>
    </html>
  );
}
